name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '12.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install jupyterlab
        python -m pip install cookiecutter
    - name: Create pure frontend extension
      run: |
        cookiecutter . --no-input
        cd jupyterlab_myextension
        jupyter labextension install .
        jupyter lab clean
        jupyter labextension link .
        python -m jupyterlab.browser_check
